# Generated by Django 3.0.8 on 2020-07-08 01:56

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200418_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(default=False, max_length=2),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default=False, max_length=100, verbose_name='state'),
        ),
    ]
