# Generated by Django 3.0.8 on 2020-07-13 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_stock'),
        ('orders', '0009_auto_20200713_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_category', to='shop.Product'),
        ),
    ]
