# Generated by Django 3.0.8 on 2020-07-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200713_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
