# Generated by Django 3.0.8 on 2020-07-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20200713_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
