# Generated by Django 3.0.8 on 2020-07-16 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200716_1144'),
        ('orders', '0016_auto_20200715_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_size', to='shop.Size'),
        ),
    ]
